spring.application.name=flood-monitoring-api
server.port=8081

spring.datasource.url=jdbc:h2:mem:flooddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=fiap-global-solution-2026-secret-key-architecture-soa
jwt.expiration=3600000

external.weather.base-url=https://api.open-meteo.com/v1

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
