CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(160) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL
);

CREATE TABLE monitored_regions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(2) NOT NULL,
    neighborhood VARCHAR(120) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    river_name VARCHAR(120),
    risk_level VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    description VARCHAR(500)
);

CREATE TABLE risk_analysis_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id BIGINT NOT NULL,
    analyzed_at TIMESTAMP NOT NULL,
    rainfall_mm DOUBLE PRECISION NOT NULL,
    temperature DOUBLE PRECISION,
    humidity INTEGER,
    external_condition VARCHAR(120),
    calculated_risk VARCHAR(20) NOT NULL,
    recommendation VARCHAR(500) NOT NULL,
    CONSTRAINT fk_risk_region FOREIGN KEY (region_id) REFERENCES monitored_regions(id) ON DELETE CASCADE
);

CREATE TABLE flood_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id BIGINT NOT NULL,
    title VARCHAR(160) NOT NULL,
    message VARCHAR(600) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    resolved_at TIMESTAMP,
    CONSTRAINT fk_alert_region FOREIGN KEY (region_id) REFERENCES monitored_regions(id) ON DELETE CASCADE
);

CREATE INDEX idx_regions_city_state ON monitored_regions(city, state);
CREATE INDEX idx_risk_region_analyzed_at ON risk_analysis_records(region_id, analyzed_at);
CREATE INDEX idx_alert_region_status ON flood_alerts(region_id, status);
